# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Assistant(object):
    def setupUi(self, Assistant):
        Assistant.setObjectName("Assistant")
        Assistant.resize(885, 625)
        Assistant.setStyleSheet("Assistant{\n"
"    background-color:rgb(56,58,89),\n"
"    border-radius:10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Assistant)
        self.centralwidget.setObjectName("centralwidget")
        self.QFrame = QtWidgets.QFrame(self.centralwidget)
        self.QFrame.setGeometry(QtCore.QRect(10, 10, 871, 611))
        self.QFrame.setStyleSheet("QFrame{\n"
"    border-radius:16px;\n"
"    background-color:black;\n"
"    margin-top:10px;\n"
"    margin-bottom:10px;\n"
"    margin-right:10px;\n"
"    margin-left:10px;\n"
"}")
        self.QFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QFrame.setObjectName("QFrame")
        self.label = QtWidgets.QLabel(self.QFrame)
        self.label.setGeometry(QtCore.QRect(4, 5, 851, 601))
        self.label.setStyleSheet("border-radius:10px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../aaass.gif"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.QFrame)
        self.label_2.setGeometry(QtCore.QRect(280, 490, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color:white;\n"
"    border-color:black;\n"
"    text-align:center;\n"
"    font-size:26px;\n"
"}")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.QFrame)
        self.pushButton.setGeometry(QtCore.QRect(740, 30, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"color:rgb(254,121,199);\n"
"background-color:rgb(56,58,89);\n"
"border : 2px solid rgb(56,58,89);\n"
"border-radius : 10px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        Assistant.setCentralWidget(self.centralwidget)

        self.retranslateUi(Assistant)
        QtCore.QMetaObject.connectSlotsByName(Assistant)

    def retranslateUi(self, Assistant):
        _translate = QtCore.QCoreApplication.translate
        Assistant.setWindowTitle(_translate("Assistant", "MainWindow"))
        self.pushButton.setText(_translate("Assistant", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Assistant = QtWidgets.QMainWindow()
    ui = Ui_Assistant()
    ui.setupUi(Assistant)
    Assistant.show()
    sys.exit(app.exec_())
