# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Assistant(object):
    def setupUi(self, Assistant):
        Assistant.setObjectName("Assistant")
        Assistant.resize(897, 581)
        self.centralwidget = QtWidgets.QWidget(Assistant)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, 5, 931, 571))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../aaass.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        Assistant.setCentralWidget(self.centralwidget)

        self.retranslateUi(Assistant)
        QtCore.QMetaObject.connectSlotsByName(Assistant)

    def retranslateUi(self, Assistant):
        _translate = QtCore.QCoreApplication.translate
        Assistant.setWindowTitle(_translate("Assistant", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Assistant = QtWidgets.QMainWindow()
    ui = Ui_Assistant()
    ui.setupUi(Assistant)
    Assistant.show()
    sys.exit(app.exec_())
